recipe = {
    "_id": "light_testing_recipe",
    "format": "simple",
    "operations": [
        [
            0.0,
            "light_intensity_red",
            1
        ],
        [
            0.0,
            "light_intensity_blue",
            0
        ],
        [
            0.0,
            "light_intensity_white",
            0
        ],
        [
            36.0,
            "light_intensity_red",
            0
        ],
        [
            36.0,
            "light_intensity_blue",
            0
        ],
        [
            36.0,
            "light_intensity_white",
            0
        ],
        [
            72.0,
            "light_intensity_red",
            1
        ],
        [
            72.0,
            "light_intensity_blue",
            0
        ],
        [
            72.0,
            "light_intensity_white",
            0
        ],
        [
            108.0,
            "light_intensity_red",
            0
        ],
        [
            108.0,
            "light_intensity_blue",
            0
        ],
        [
            108.0,
            "light_intensity_white",
            0
        ],
        [
            144.0,
            "light_intensity_red",
            1
        ],
        [
            144.0,
            "light_intensity_blue",
            0
        ],
        [
            144.0,
            "light_intensity_white",
            0
        ],

        [
            180.0,
            "light_intensity_red",
            0
        ],
        [
            180.0,
            "light_intensity_blue",
            0
        ],
        [
            180.0,
            "light_intensity_white",
            0
        ],

        [
            216.0,
            "light_intensity_red",
            1
        ],
        [
            216.0,
            "light_intensity_blue",
            0
        ],
        [
            216.0,
            "light_intensity_white",
            0
        ],
    ]
}
